! $Id$
      module ESMF_TimeMgmtMod
!===============================================================================
!BOP
! !MODULE: ESMF_TimeMgmtMod
!
! !USES:
      use ESMF_BasicUtilMod
      use ESMF_ErrorMod
      use ESMF_TimeMod
      use ESMF_DateMod
      use ESMF_TimeMgrMod
      use ESMF_AlarmMod
!
! !DESCRIPTION:
! Contains all of the time Management utilities.
!EOP
!===============================================================================

      implicit none


      end module ESMF_TimeMgmtMod













