# $Id$ 

ALL: lib 

CFLAGS    =
FFLAGS    =
SOURCEC	  = mpi.c
SOURCEF	  = 
SOURCEH	  = mpi.h mpif.h
OBJSC     = $(addsuffix .o, $(basename $(SOURCEC)))
OBJSF     = $(addsuffix .o, $(basename $(SOURCEF)))
MANSEC	  = Timeobj
LIBBASE	  = libmpiuni
DIRS	  = 
LOCDIR	  = src/Infrastructure/mpiuni/
CLEANFILES = $(LIBNAME) 

include ${ESMF_DIR}/build/${ESMF_ARCH}/base






